### ISSUE TITLE
function comments looks weird

### ISSUE THREAD

**Issue by smu4242** [Adam13531/BotLand#121]
**Steps to reproduce**
I think you need a function with a longer comment

**Expected outcome**
the comment should be in the box

**Actual outcome**
the comment appears on the top right of the screen
https://imgur.com/Zu1qq9i

**Browser information**
{"name":"Chrome","chrome":true,"version":"61.0","blink":true,"windows":true,"a":true}

**In-game information**
Player ID: 36
Player name: smu4242

**Comment by Adam13531** [comment]
I've upgraded Blockly since this was filed and I think the bug has been fixed; I can't repro it any longer.

**Comment by smu4242** [comment]
Nope, still happens.

- attack
- create a new blueprint
- click "script" on bottom left"
- create a new script
- select Advanced -> Functions
- Drag the first thing in
- Click on the "?"
- Copy "Describe this function..."
- Past it 3 times
- It looks like this: https://i.imgur.com/hxmTKb9.png

**Comment by HiDeoo** [comment]
Re-opening temporarily but I can definitely say it's fixed on my end (I think my repro is correct).

![screen shot 2018-05-13 at 18 09 14](https://user-images.githubusercontent.com/494699/39969192-d5e8a398-56d8-11e8-8d02-4f864af2ee0e.png)

Could you give us a little bit more details, like, are you still using the same version of Chrome that you were using in the initial post?

I'm using Chrome 68 on macOS and it's not an issue on it.

**Comment by smu4242** [comment]
**Browser information**
{"name":"Chrome","chrome":true,"version":"66.0","blink":true,"windows":true,"a":true}

**In-game information**
Client version: 0.2.26
Player ID: 36
Player name: smu4242

It does not happen on https://developers.google.com/blockly/

Here's a more detailed gif: https://i.imgur.com/rBkOyhj.gifv (don't mind the offset of the cursor, that's just a recording issue).
As you can see, it only happens when the box is too small for the text.

I have tried to debug this, but to no avail.
To me it seems like an svg bug (but I'm not sure).
The <textbox x=.. y=..> seem to be interpreted as absolute, but I cannot see why.

**Comment by Skedog** [comment]
As far as I can tell, this no longer happens as of Chrome `version 69.0.3497.100`. Closing for now, feel free to re-open if it happens again.

![](https://i.gyazo.com/a51da1c10312a89eac3cb77d6a21ef12.png)
